In [5]:
import pandas as pd

In [7]:
df_train=pd.read_csv("data/train.csv")
df_train.head()

,MONTH,DAY_OF_WEEK,DEP_DEL15,DEP_TIME_BLK,DISTANCE_GROUP,SEGMENT_NUMBER,CONCURRENT_FLIGHTS,NUMBER_OF_SEATS,CARRIER_NAME,AIRPORT_FLIGHTS_MONTH,...,PREVIOUS_AIRPORT,PRCP,SNOW,SNWD,TMAX,AWND,CARRIER_HISTORICAL,DEP_AIRPORT_HIST,DAY_HISTORICAL,DEP_BLOCK_HIST
0,7,7,0,1500-1559,3,3,26,160,American Airlines Inc.,19534,...,Chicago O'Hare International,0.00,0.0,0.0,95.0,4.25,0.237709,0.273236,0.222538,0.255479
1,4,1,0,1300-1359,4,4,63,50,SkyWest Airlines Inc.,18788,...,El Paso International,0.00,0.0,0.0,71.0,11.41,0.154651,0.121849,0.237972,0.197503
2,11,4,0,0001-0559,2,1,3,76,American Eagle Airlines Inc.,1148,...,NONE,0.00,0.0,0.0,54.0,0.45,0.117559,0.187867,0.139886,0.060327
3,3,2,0,1500-1559,7,5,14,143,Southwest Airlines Co.,7612,...,San Jose International,0.00,0.0,0.0,64.0,8.05,0.204389,0.141446,0.132868,0.202037
4,7,3,0,0800-0859,1,2,85,50,American Eagle Airlines Inc.,29376,...,Cincinnati/Northern Kentucky International,0.01,0.0,0.0,94.0,10.51,0.203263,0.193761,0.203027,0.113050

In [9]:
df_train = df_train[["MONTH", "DAY_OF_WEEK", "DEP_DEL15", "CONCURRENT_FLIGHTS", "CARRIER_NAME", "PRCP", "SNOW"]]
df_train.head()

,MONTH,DAY_OF_WEEK,DEP_DEL15,CONCURRENT_FLIGHTS,CARRIER_NAME,PRCP,SNOW
0,7,7,0,26,American Airlines Inc.,0.00,0.0
1,4,1,0,63,SkyWest Airlines Inc.,0.00,0.0
2,11,4,0,3,American Eagle Airlines Inc.,0.00,0.0
3,3,2,0,14,Southwest Airlines Co.,0.00,0.0
4,7,3,0,85,American Eagle Airlines Inc.,0.01,0.0